---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Forestry
- type: document
  path: src/index.md
  label: starter
- type: document
  path: src/about/index.md
  label: About
- type: document
  path: src/apply/index.md
  label: Apply
- type: document
  path: src/blog/index.md
  label: Blog
- type: document
  path: src/contact/index.md
  label: Contact
- type: document
  path: src/donate/index.md
  label: Donate
- type: document
  path: src/events/index.md
  label: Events
- type: document
  path: src/impact/index.md
  label: Impact
- type: document
  path: src/programs/index.md
  label: Programs
- type: document
  path: src/resources/index.md
  label: Resources
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
